### ISSUE TITLE
你好，可不可以发你的数据库给我学习一下？谢谢

### ISSUE THREAD

**Issue by nasasky** [CongerZeng/vue_thinkphp_webapp#1]

**Comment by Eikthymir** [comment]
不好意思，一直没看项目，不知道还真的有人会看我的项目，我现在上传数据库文件，谢谢

**Comment by nasasky** [comment]
你好，你那个连接接口数据位置哪里改的，我改config里面那个index那，怎么我访问还是本地的接口的？谢谢

**Comment by Eikthymir** [comment]
> 你好，你那个连接接口数据位置哪里改的，我改config里面那个index那，怎么我访问还是本地的接口的？谢谢

修改config/index.js 下的proxyTable的target，因为有些接口写的不同你或许需要自己替换
